PlayerChance: 0.3
MessageRange: 32
MessagePrefix: '&4&o'
Messages:
- 'No reason to lose your head, %player%!'
- 'Don''t get ahead of yourself, %player%!'
- 'That''s not the way to get ahead in life, %player%!'
- 'It''s a shame %player% wasn''t more headstrong.'
- '%player% will never be the head of a major corporation.'
- 'Heading somewhere, %player%?'