PlayerChance: 10
MobChance: 5000
Messages:
- '&4&oNo reason to lose your head.'
- '&4&oDon''t get ahead of yourself.'
- '&4&oThat''s not the way to get ahead in life.'
- '&4&oIt''s a shame you weren''t more headstrong.'
- '&4&oYou''l never be the head of a major corporation.'
- '&4&oHeading somewhere?'