main: com.winthier.headhunter.HeadHunterPlugin
name: HeadHunter
version: 0.1
api-version: 1.13
description: Make a player head drop when people die in pvp
author: StarTux
website: https://cavetale.com
depend: []
commands:
  headhunter:
    description: Debug command
    permission: headhunter.headhunter
    usage: /headhunter reload
permissions:
  headhunter.headhunter:
    description: Use the /headhunter command
    default: op